name: push action develop

on:
  push:
    branches:
      - develop
      - action/push_develop

jobs:
  push_develop:
    name: push develop
    #if: ${{ github.repository_owner == 'gongnyaa' }}
    runs-on: ubuntu-latest
    env:
      ORG_REPO_TOKEN: ${{ secrets.ORG_REPO_TOKEN }}
    steps:
      - run: |
          git clone --depth 1 -b develop https://gongnyaa:$ORG_REPO_TOKEN@github.com/gongnyaa/Eigomonogatari.git
          
          cd Eigomonogatari
        
          git config --global user.name 'gongnyaa'
          git config --global user.email 'kaneko.teruaki@gmail.com'

          git remote add upstream https://gongnyaa:$ORG_REPO_TOKEN@github.com/freedomcreators/sample-destination.git

          git branch

          git push upstream -f develop
