name: push action develop

on:
  push:
    branches:
      - develop
      - action/push_develop

jobs:
  push_develop:
    name: push develop
    #if: ${{ github.repository_owner == 'gongnyaa' }}
    runs-on: ubuntu-latest
    env:
      #FREEDOM_CREATORS_API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      #- uses: actions/checkout@v2
      - run: |
          git clone https://estellise-yukihime:$API_TOKEN@github.com/snow-eigo/sample-action.git

          cd sample-action

          git config --global user.name 'estellise-yukihime'
          git config --global user.email 'shiranoyukihime@gmail.com'

          git remote -v

          echo $API_TOKEN

          git remote set-url origin https://estellise-yukihime:$API_TOKEN@github.com/snow-eigo/sample-action-destination.git

          git remote -v

          git branch
