name: push action develop

on:
  push:
    branches:
      - develop
      - action/push_develop

jobs:
  push_develop:
    name: push develop
    #if: ${{ github.repository_owner == 'gongnyaa' }}
    runs-on: ubuntu-latest
    env:
      #FREEDOM_CREATORS_API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name 'gongnyaa'
          git config --global user.email 'kaneko.teruaki@gmail.com'

          git remote -v

          echo $FREEDOM_CREATORS_API_TOKEN_GITHUB

          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/freedomcreators/sample-destination.git

          git remote -v

          git push origin
